USE ROLE SECURITYADMIN;

CREATE USER IF NOT EXISTS SNOWFLAKE_LAB_01_USER
  PASSWORD = 'Temp#LabUser123!'      -- change after first login
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = SNOWFLAKE_LAB_DE_ROLE
  DEFAULT_WAREHOUSE = SNOWFLAKE_LAB_DE_WH
  COMMENT = 'Dedicated user for SNOWFLAKE_LAB semi-structured data lab';
