USE ROLE SECURITYADMIN;

-- 1) Create the lab execution role
CREATE ROLE IF NOT EXISTS SNOWFLAKE_LAB_DE_ROLE;

-- 2) Data access (read-only)
GRANT USAGE ON DATABASE SNOWFLAKE_LAB_TRAINING_DB TO ROLE SNOWFLAKE_LAB_DE_ROLE;
GRANT USAGE ON SCHEMA  SNOWFLAKE_LAB_TRAINING_DB.WEATHER TO ROLE SNOWFLAKE_LAB_DE_ROLE;

GRANT SELECT ON TABLE SNOWFLAKE_LAB_TRAINING_DB.WEATHER.SNOWFLAKE_LAB_ISD_2019_TOTAL
  TO ROLE SNOWFLAKE_LAB_DE_ROLE;

GRANT SELECT ON TABLE SNOWFLAKE_LAB_TRAINING_DB.WEATHER.SNOWFLAKE_LAB_ISD_2019_DAILY
  TO ROLE SNOWFLAKE_LAB_DE_ROLE;

-- 3) Warehouse permissions (script uses/alter/suspend warehouse)
GRANT USAGE   ON WAREHOUSE SNOWFLAKE_LAB_DE_WH TO ROLE SNOWFLAKE_LAB_DE_ROLE;
GRANT OPERATE ON WAREHOUSE SNOWFLAKE_LAB_DE_WH TO ROLE SNOWFLAKE_LAB_DE_ROLE;
GRANT MODIFY  ON WAREHOUSE SNOWFLAKE_LAB_DE_WH TO ROLE SNOWFLAKE_LAB_DE_ROLE;

-- 4) Assign the role to your user (replace with your login)
GRANT ROLE SNOWFLAKE_LAB_DE_ROLE TO USER SNOWFLAKE_LAB_01_USER;

-- Verify
SHOW GRANTS TO USER SNOWFLAKE_LAB_01_USER;
SHOW GRANTS TO ROLE SNOWFLAKE_LAB_DE_ROLE;

