USE ROLE SYSADMIN;

USE DATABASE SNOWFLAKE_LAB_TRAINING_DB;
USE SCHEMA WEATHER;
USE WAREHOUSE SNOWFLAKE_LAB_DE_WH;

-- 1) Create tables 
CREATE OR REPLACE TABLE SNOWFLAKE_LAB_ISD_2019_TOTAL (
  V VARIANT,
  T TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE SNOWFLAKE_LAB_ISD_2019_DAILY (
  V VARIANT,
  T DATE
);